### ISSUE TITLE
[react-native] `react-navigation` support

### ISSUE THREAD

**Issue by civilizeddev** [shadaj/slinky#209]
Hi, thank you for your contributions.

I want to use `slinky` on my `react-native` project.
I hope I would be a deep user of slinky in the future.

But I faced the problem described below:

I use [react-navigation](https://reactnavigation.org/en/).

## Given some components below,

```
@react class HomeScreen extends Component {
  ...
}

@react class OneScreen extends Component {
  ...
}

@react class TwoScreen extends Component {
  ...
}
```

## In ES6, I can do like this:

```
...

import {  createAppContainer, createBottomTabNavigator } from "react-navigation"

const navigator = createBottomTabNavigator({
  "home": HomeScreen,
  "one": OneScreen,
  "two": TwoScreen
})

// NavigationContainer
const NavigationContainer = createAppContainer(navigator)

...

render () {
  return <NavigationContainer />
}
```

## I tried the same in Scala.js with Slinky

```
@JSImport("react-navigation", JSImport.Default)
@js.native
object ReactNavigation extends js.Object {

  def createBottomTabNavigator(configMap: js.Dictionary[js.Any]): NavigationContainer = js.native

  def createAppContainer(navigationContainer: NavigationContainer): NavigationContainer = js.native

}

@js.native
trait NavigationContainer extends StatelessComponent

...

// didn't compile with red errors.
val navigator = createBottomTabNavigator(
  Dictionary(
    "home" -> HomeScreen,
    "one" -> OneScreen,
    "two" -> TwoScreen
  )
)

val NavigationContainer = createAppContainer(navigator)

...

// didn't compile with red errors.
def render(): ReactElement = {
  NavigationContainer
}
```

## Please help

I'm not sure whether this can be resolved in the current version.
I think I did something wrong. Please help me do right.

Plus,
I use IntelliJ IDEA. `@react` annotation works well and succeed to compile in sbt. but in editor it shows red errors, and type inference doesn't work. It makes me confused and frustrated. Any idea?

Thank you.

**Comment by shadaj** [comment]
Hi, looks like there are a couple somewhat separate issues coming into picture here.

First, since you are passing in React component classes into `createBottomTabNavigator`, it needs to be declared as `def createBottomTabNavigator(configMap: js.Dictionary[ReactComponentClass]` so that Slinky can perform the appropriate conversions into what React libraries expect when taking in component references.

Then, with `NavigationContainer`, since this is a component defined in a React JS library, you must declare it as an `ExternalComponent` following the guidelines at https://slinky.shadaj.me/docs/external-components/. Then, you will be able to call `NavigationContainer(prop1 = foo, prop2 = bar, etc...)`.

But in general, it is possible to match the ES6 code with Slinky code, with a few adjustments to what you have!

For IntelliJ, have you followed the instructions at https://slinky.shadaj.me/docs/installation/ under "IntelliJ Support"? Setting things up require a few manual steps right now, this will improve with the next version of IntelliJ's Scala Plugin however.

**Comment by civilizeddev** [comment]
Thanks for quick reply.

## `ExternalComponent` for `HOC`?

It looks like this is more complicated case:

I cannot define `NavigationContainer` as an `ExternalComponent` in normal way because it is an HOC, derived from inside `function createNavigationContainer`.

```
/**
 * Create an HOC that injects the navigation and manages the navigation state
 * in case it's not passed from above.
 * This allows to use e.g. the StackNavigator and TabNavigator as root-level
 * components.
 */
export default function createNavigationContainer(Component) {
  class NavigationContainer extends React.Component {
    ...
  }
  
  return NavigationContainer
}
```

## `ReactComponentClass[P]` or @react annotation issue?

I found `ReactComponentClass[P]` takes type parameter `P`.
For now I set it as `Unit`.

```
def createBottomTabNavigator(configMap: js.Dictionary[ReactComponentClass[Unit]]
```

still not working.

```
[IJ]sbt:palmcove> compile
[info] Compiling 10 Scala sources to /Users/david/Documents/GitHub/palmcove-app-rn-scalajs/target/scala-2.12/classes ...
[error] /Users/david/Documents/GitHub/palmcove-app-rn-scalajs/src/main/scala/io/palmcove/App.scala:28:17: type mismatch;
[error]  found   : io.palmcove.HomeScreen.type
[error]  required: slinky.core.ReactComponentClass[Unit]
[error]       "home" -> HomeScreen,
[error]                 ^
[error] /Users/david/Documents/GitHub/palmcove-app-rn-scalajs/src/main/scala/io/palmcove/App.scala:29:16: type mismatch;
[error]  found   : io.palmcove.OneScreen.type
[error]  required: slinky.core.ReactComponentClass[Unit]
[error]       "one" -> OneScreen,
[error]                ^
[error] /Users/david/Documents/GitHub/palmcove-app-rn-scalajs/src/main/scala/io/palmcove/App.scala:30:16: type mismatch;
[error]  found   : io.palmcove.TwoScreen.type
[error]  required: slinky.core.ReactComponentClass[Unit]
[error]       "two" -> TwoScreen
[error]                ^
```

## Need help

`react-navigation` is mostly used library for `react-native` apps.
I think it's good to have a dedicated documentation in [React Native and VR](https://slinky.shadaj.me/docs/native-and-vr/) section as a case study.

**Comment by shadaj** [comment]
In the case of a HOC, you'll need to write some custom logic to call the `createNavigationContainer` method and then wrap the result in an `ExternalComponent`. See https://github.com/shadaj/slinky/blob/master/core/src/main/scala/slinky/core/facade/ReactContext.scala for an example of a similar situation with functions returning components.

For `ReactComponentClass`, the parameter `P` is the props type (I'm guessing your components take some non-`Unit` props which is why the conversion didn't take place), but since here we don't care what the props are we can type the parameter as `js.Dictionary[ReactComponentClass[_]]`.
