### ISSUE TITLE
Component setState cannot update empty Optional values

### ISSUE THREAD

**Issue by at1as** [shadaj/slinky#244]
Hi,

Thanks for the work you put into Slinky, I've been using it with great success! I am however encountering an issue when updating a component's state from an existing option value to an empty option value.

I've put together an [example repo](https://github.com/at1as/react-slinky-setstate) to show the behaviour I'm encountering ([see: App.scala](https://github.com/at1as/react-slinky-setstate/blob/master/src/main/scala/hello/world/App.scala)). This is built off of the provided `create-react-scala-app` example, and only modifies `App.scala` to demonstrate the behaviour.

Essentially, given a State that includes an Option as a parameter:
```scala
case class State(optionString: Option[String])
```
I can update the state to `Some(...)`, but not `None`:

```scala
setState(_.copy(optionString = Some("111")), () => { println("value is ${state.optionString}") })

value is Some(111)

setState(_.copy(optionString = Some("222")), () => { println("value is ${state.optionString}") }))

value is Some(222)

setState(_.copy(optionString = None)), () => { println("value is ${state.optionString}") })

value is Some(222)

setState(_.copy(optionString = Some("333")), () => { println("value is ${state.optionString}") })

value is Some(333)
```

**Observations**

The behaviour is identical when:
* wrapping the option in another option: `optionString: Option[Option[String]]`
* providing `Option.empty[String]` instead of `None`
* rebuilding the State from the case class (not using _.copy)
* updating multiple params simulataneously, versus only one

However, it does seem to work if I wrap the Option under a case class and use that:
```
case class SafeOption(value: Option[String])
case class State(optionString: SafeOption)
setState(_.copy(optionString = SafeOption(None)), () => { println("value is ${state.optionString.value}") }))

value is None
``` 

**Environment**

Sbt:
```
❯ sbt -v
[process_args] java_version = '8'
# Executing command line:
java
-Xms1024m
-Xmx1024m
-XX:ReservedCodeCacheSize=128m
-XX:MaxMetaspaceSize=256m
-jar
/usr/local/Cellar/sbt/1.2.8/libexec/bin/sbt-launch.jar
```

Scala:
```
❯ scala -version
Scala code runner version 2.12.1
```

Platform
* MacOS 10.14

**Comment by shadaj** [comment]
Hi @at1as, thanks for the super detailed bug report! The specific setup and observations made it much easier to understand what is going on.

I actually know *exactly* what is going on here: a subtle interaction between how `setState` works and how `Option` is emitted when hot-reloading is enabled. In React, `setState` ignores updating any properties whose values are `js.undefined`, which is useful in JS code to only update a few specific values in the state object. Unfortunately, this runs into problems with how Slinky emits `Option` when hot reloading is enabled, because the current implementation of `optionWriter` writes `js.undefined` when the value is `None`. This should be easily fixable by emitting `null` instead, which anyways better matches the idea of what an `Option` is. To write `js.undefined`, the `js.UndefOr` writer will still emit `js.undefined` when the value passed in is empty.

**Comment by at1as** [comment]
Awesome, thanks for the quick turnaround!
