### ISSUE TITLE
Support/document faster Unit test execution in Intellij

### ISSUE THREAD

**Issue by evbo** [shadaj/slinky#246]
Would it be within scope to enhance and/or document how the Intellij plugin can run scala.js tests without needing SBT?

If not, then perhaps we could just add to the documentation to check the box in Intellij's scalatest runtime configuration for: `Use sbt`

But there's still at least 17 seconds of overhead (fast compiling, etc.) before my tests run in intellij. Is there more optimizations that can made to speed up test driven development in Intellij, or is that the best I'm gonna do?

**Comment by shadaj** [comment]
I think changing how IntelliJ runs tests is pretty out of scope. I think Bloop is probably the best opportunity to speed up the testing flow, but I'm not super sure what's the status on Scala.js support there.

Closing as won't fix for now, since there's not much we can do from Slinky to improve this. If you do come across any optimizations however, it would be awesome to integrate them into `create-react-scala-app`!

**Comment by evbo** [comment]
i understand, thanks for confirming. unit testing with scalajs is one hidden cost I didn't at first anticipate. But at least it works!
