### ISSUE TITLE
Using scala collections as a state can cause runtime errors

### ISSUE THREAD

**Issue by oleg-py** [shadaj/slinky#294]
I have a slightly modified scalafiddle sample here with a demonstration:
https://scalafiddle.io/sf/7Y0wvQp/0

Clicking "Add #1" causes component to unmount with the following exception logged in browser console:
```
uncaught exception: scala.scalajs.runtime.UndefinedBehaviorError: An undefined behavior was detected: List() is not an instance of java.lang.Integer
```

There are no compile-time warnings/errors, and this hit me by surprise yesterday (with 0.6.2 version - the behavior is unchanged).

This probably happens because `setState` uses runtime overload resolution to tell between a function-call version vs. object version, and a `Seq` is an instance of `Function1`. Actually, every stdlib collection is (Sets are `A => Boolean`, Maps and Seqs are `PartialFunction`s from keys/indices to the values). And here, slinky is trying to call `List.apply` with an instance of previous state, which is an empty `List()`.

**Comment by shadaj** [comment]
Thanks for the detailed bug report @oleg-py! I think I know what's going on here. Right now, all the overloaded `setState` methods have the same `@JSName` (https://github.com/shadaj/slinky/blob/master/core/src/main/scala/slinky/core/DefinitionBase.scala#L60), which forces Scala.js to use runtime type checking to determine which implementation to use, which is going wrong since erasure leaves ambiguity with whether to treat the value as `State` or a `Function1`. Giving different names to each overloaded version should be enough to fix this.
