### ISSUE TITLE
Hot reloading doesn't work with SJS 1.0

### ISSUE THREAD

**Issue by Katrix** [shadaj/slinky#331]
Probably got something to do with trying to still access the global object here.
https://github.com/shadaj/slinky/blob/master/hot/src/main/scala/slinky/hot/package.scala#L11

**Comment by ryneflood** [comment]
just ran into the same issue. Commenting out lines 10-12 gets it working for me, but I'm sure isn't an _actual_ solution: https://github.com/shadaj/slinky/blob/master/hot/src/main/scala/slinky/hot/package.scala#L10

Like pointed out on Gittter by @oyvindberg it's likely because of this:
http://www.scala-js.org/news/2020/02/25/announcing-scalajs-1.0.0/#accessing-a-member-that-is-not-declared-causes-a-referenceerror-to-be-thrown
