### ISSUE TITLE
Unclear documentation on interop with JS

### ISSUE THREAD

**Issue by nadenf** [shadaj/slinky#554]
I have an external component:
```
import slinky.core.ExternalComponent
import slinky.core.annotations.react

import scala.scalajs.js
import scala.scalajs.js.annotation.JSImport
import scala.scalajs.js.|

@JSImport("@nivo/waffle", "ResponsiveWaffleCanvas")
@js.native
object ReactWaffle extends js.Object

@react object Waffle extends ExternalComponent {
  case class Props(tooltip: js.UndefOr[js.Object => ReactComponentClass[_] | ReactElement] = js.undefined)
  override val component = ReactWaffle
}
```

But then when I try and use it I get the following error message:
```
Objects are not valid as a React child. 

Where the type of the tooltip component is: slinky_core_KeyAndRefAddingStage
```

I can't seem to pass in either a component e.g. MyComponent or even a div(). It would be good to add this to the interop documentation.

**Comment by shadaj** [comment]
Ah, the issue here is most likely that the props type is using the JS union type, which relies on runtime checks to determine which writer to use. But one of the branches is a native JS type is `ReactElement` which can't be checked against at runtime, so the writer passes through as is.

Could you try using the Scala `Either` type? That lets us know exactly which branch needs to be used at runtime. If that still doesn't work, there may be a bug here.

**Comment by nadenf** [comment]
I've put together a test case here: https://github.com/harana-oss/slinky-554

It relies on a private SBT plugin so you will need to update build.sbt to rebuild everything.

But you should be able to just run:
```
python -m SimpleHTTPServer
```

From the root directory and see the issue. When you hover over the squares it will crash.
